// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu64cEpB15SjV8xTQEwi1YgoPruxL3-nU',
    appId: '1:1081864532778:web:3cbceae7da7f9129b0a453',
    messagingSenderId: '1081864532778',
    projectId: 'learnza',
    authDomain: 'learnza.firebaseapp.com',
    storageBucket: 'learnza.firebasestorage.app',
    measurementId: 'G-GT3ZX5RMRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-TWa5qSTg-OkydTOBrEtJuJ3cHoayjLs',
    appId: '1:1081864532778:android:2522ac606433bc8fb0a453',
    messagingSenderId: '1081864532778',
    projectId: 'learnza',
    storageBucket: 'learnza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI_2bpk0t3vvLV0HCsCO4qpgxfjo0P5c4',
    appId: '1:1081864532778:ios:33468e20e8494b6fb0a453',
    messagingSenderId: '1081864532778',
    projectId: 'learnza',
    storageBucket: 'learnza.firebasestorage.app',
    iosBundleId: 'com.example.learnza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI_2bpk0t3vvLV0HCsCO4qpgxfjo0P5c4',
    appId: '1:1081864532778:ios:33468e20e8494b6fb0a453',
    messagingSenderId: '1081864532778',
    projectId: 'learnza',
    storageBucket: 'learnza.firebasestorage.app',
    iosBundleId: 'com.example.learnza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu64cEpB15SjV8xTQEwi1YgoPruxL3-nU',
    appId: '1:1081864532778:web:2d6cad716f34d615b0a453',
    messagingSenderId: '1081864532778',
    projectId: 'learnza',
    authDomain: 'learnza.firebaseapp.com',
    storageBucket: 'learnza.firebasestorage.app',
    measurementId: 'G-RMLFEBKHM9',
  );
}
