// Mocks generated by Mockito 5.4.5 from annotations
// in learnza/test/screen/auth/forgot_password_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:learnza/model/users/users_model.dart' as _i5;
import 'package:learnza/providers/auth_provider.dart' as _i3;
import 'package:learnza/service/firebase_service.dart' as _i2;
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

@GenerateNiceMocks([MockSpec<_i3.AuthProvider>()])
class _FakeFirebaseService_0 extends _i1.SmartFake
    implements _i2.FirebaseService {
  _FakeFirebaseService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i3.AuthProvider {
  @override
  _i2.FirebaseService get firebaseService => (super.noSuchMethod(
        Invocation.getter(#firebaseService),
        returnValue: _FakeFirebaseService_0(
          this,
          Invocation.getter(#firebaseService),
        ),
        returnValueForMissingStub: _FakeFirebaseService_0(
          this,
          Invocation.getter(#firebaseService),
        ),
      ) as _i2.FirebaseService);

  @override
  bool get obscure => (super.noSuchMethod(
        Invocation.getter(#obscure),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set obscure(bool? _obscure) => super.noSuchMethod(
        Invocation.setter(
          #obscure,
          _obscure,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isLoading(bool? _isLoading) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          _isLoading,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void toggleObscure() => super.noSuchMethod(
        Invocation.method(
          #toggleObscure,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> getUser(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [uid],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.UsersModel?> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i5.UsersModel?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.UsersModel?>.value(),
      ) as _i4.Future<_i5.UsersModel?>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createAdminRegisteration({
    required String? email,
    required String? username,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAdminRegisteration,
          [],
          {
            #email: email,
            #username: username,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createTeacherRegistration({
    required String? email,
    required String? fullName,
    required String? courseId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTeacherRegistration,
          [],
          {
            #email: email,
            #fullName: fullName,
            #courseId: courseId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createStudentRegistration({
    required String? email,
    required String? fullName,
    List<String>? enrolledCourseIds,
    required String? batch,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStudentRegistration,
          [],
          {
            #email: email,
            #fullName: fullName,
            #enrolledCourseIds: enrolledCourseIds,
            #batch: batch,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> forgotPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
