// Mocks generated by Mockito 5.4.5 from annotations
// in learnza/test/routes/app_route_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:firebase_database/firebase_database.dart' as _i5;
import 'package:firebase_storage/firebase_storage.dart' as _i3;
import 'package:learnza/model/app_enums.dart' as _i7;
import 'package:learnza/service/firebase_service.dart' as _i6;
import 'package:learnza/service/internet_connectivity_service.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseAuth_0 extends _i1.SmartFake implements _i2.FirebaseAuth {
  _FakeFirebaseAuth_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseStorage_1 extends _i1.SmartFake
    implements _i3.FirebaseStorage {
  _FakeFirebaseStorage_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_2 extends _i1.SmartFake
    implements _i4.FirebaseFirestore {
  _FakeFirebaseFirestore_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseDatabase_3 extends _i1.SmartFake
    implements _i5.FirebaseDatabase {
  _FakeFirebaseDatabase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i6.FirebaseService {
  @override
  _i7.Environment get environment => (super.noSuchMethod(
        Invocation.getter(#environment),
        returnValue: _i7.Environment.development,
        returnValueForMissingStub: _i7.Environment.development,
      ) as _i7.Environment);

  @override
  _i2.FirebaseAuth get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeFirebaseAuth_0(
          this,
          Invocation.getter(#auth),
        ),
        returnValueForMissingStub: _FakeFirebaseAuth_0(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i2.FirebaseAuth);

  @override
  _i3.FirebaseStorage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeFirebaseStorage_1(
          this,
          Invocation.getter(#storage),
        ),
        returnValueForMissingStub: _FakeFirebaseStorage_1(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i3.FirebaseStorage);

  @override
  _i4.FirebaseFirestore get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeFirebaseFirestore_2(
          this,
          Invocation.getter(#database),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_2(
          this,
          Invocation.getter(#database),
        ),
      ) as _i4.FirebaseFirestore);

  @override
  _i5.FirebaseDatabase get extradb => (super.noSuchMethod(
        Invocation.getter(#extradb),
        returnValue: _FakeFirebaseDatabase_3(
          this,
          Invocation.getter(#extradb),
        ),
        returnValueForMissingStub: _FakeFirebaseDatabase_3(
          this,
          Invocation.getter(#extradb),
        ),
      ) as _i5.FirebaseDatabase);
}

/// A class which mocks [InternetConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetConnectivityService extends _i1.Mock
    implements _i8.InternetConnectivityService {
  @override
  _i9.Future<bool> checkConnectivity() => (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
}
