name: Flutter CI/CD Workflow 🛠️🚀

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'pubspec.yaml'
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type (patch/minor/major)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'
      deploy_to_play_store:
        description: "Deploy to Play Store?"
        required: true
        type: boolean
        default: false

env:
  FLUTTER_VERSION: 3.24.3
  FIREBASE_PROJECT_ID: "learnza"
  JAVA_VERSION: '17'

jobs:
  test:
    name: "Run Tests 🧪"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
            ${{ runner.tool_cache }}/flutter
            .dart_tool
            build
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Setup Env 
        run: |
          echo "${{ secrets.ENV }}" | base64 --decode > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Run Dart Fix
        run: |
          dart fix --apply
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "chore: apply dart fixes"
            git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
            git push
          fi

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: success()

  version-and-build:
    name: "Version Update & Build 🛠️"
    needs: test
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Update version
        id: version
        run: |
          # Determine release type (default to patch if not manual dispatch)
          RELEASE_TYPE="${{ github.event.inputs.release_type || 'patch' }}"
          
          # Get current version
          CURRENT_VERSION=$(grep "^version:" pubspec.yaml | awk '{print $2}' | tr -d '\r')
          echo "Current version: $CURRENT_VERSION"
          
          # Parse current version
          IFS='.' read -r -a version_parts <<< "$CURRENT_VERSION"
          MAJOR="${version_parts[0]}"
          MINOR="${version_parts[1]}"
          PATCH_BUILD="${version_parts[2]}"
          
          # Extract patch and build numbers
          PATCH=$(echo $PATCH_BUILD | cut -d+ -f1)
          BUILD=$(echo $PATCH_BUILD | cut -d+ -f2)
          
          # Increment version based on release type
          case "$RELEASE_TYPE" in
            "major")
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              BUILD=$((BUILD + 1))
              ;;
            "minor")
              MINOR=$((MINOR + 1))
              PATCH=0
              BUILD=$((BUILD + 1))
              ;;
            *)
              PATCH=$((PATCH + 1))
              BUILD=$((BUILD + 1))
              ;;
          esac
          
          # Construct new version
          NEW_VERSION="$MAJOR.$MINOR.$PATCH+$BUILD"
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
          # Update pubspec.yaml
          sed -i "s/^version: .*/version: $NEW_VERSION/" pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Keystore
        run: |
          mkdir -p android/app/keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore/upload-keystore.jks
          cat << EOF > android/key.properties
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=./keystore/upload-keystore.jks
          EOF

      - name: Generate .env file
        run: |
          echo "${{ secrets.ENV }}" | base64 --decode > .env
          echo "Verifying .env file:"
          ls -la .env

      - name: Build Android
        run: |
            flutter build apk --release --dart-define-from-file=.env
            flutter build appbundle --release --dart-define-from-file=.env
            echo "Checking build outputs:"
            ls -R build/app/outputs/

      - name: Archive build artifacts
        id: artifact-upload-step
        uses: actions/upload-artifact@v4.4.3
        with:
          name: build-artifacts
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
          overwrite: true
          if-no-files-found: error

      - name: Commit version update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pubspec.yaml
          git commit -m "chore: bump version to ${{ steps.version.outputs.new_version }}"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git push

  play-store-deploy:
    name: "Deploy to Play Store 🚀"
    needs: version-and-build
    if: ${{ github.event.inputs.deploy_to_play_store == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.0
        with:
          name: build-artifacts
          path: downloaded-artifacts/

      - name: Install Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Fastlane
        run: |
          gem install fastlane -NV

      - name: Deploy to Google Play Store
        run: |
          cd android
          fastlane supply \
            --aab "../downloaded-artifacts/bundle/release/app-release.aab" \
            --track "internal" \
            --json_key_data '${{ secrets.SERVICE_ACCOUNT_JSON }}' \
            --package_name "xyz.deepeshkalura.learnza"


  github-release:
    name: "Create GitHub Release 📦"
    needs: [version-and-build, play-store-deploy]
    if: always() && (needs.play-store-deploy.result == 'success' || needs.play-store-deploy.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4.1.0
        with:
          name: build-artifacts
          path: downloaded-artifacts/

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Find the APK
          APK_PATH=$(find . -name "app-release.apk")
          
          # Create GitHub release
          gh release create "v${{ needs.version-and-build.outputs.new_version }}" \
            "$APK_PATH" \
            --title "Release v${{ needs.version-and-build.outputs.new_version }}" \
            --notes "Automated release with version ${{ needs.version-and-build.outputs.new_version }}"