name: Manual Deploy to Play Store

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        type: choice
        options:
          - internal_test
          - production
      version_bump:
        description: 'Version Bump Type'
        required: true
        type: choice
        options:
          - build
          - feature
        default: 'build'
jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
      
      - name: Run Version Increment Script
        id: version
        run: |
          python version_script.py
          NEW_VERSION=$(grep "^version:" pubspec.yaml | awk '{print $2}')
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

  build-and-deploy:
    needs: prepare-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Generate .env file
        run: |
          echo "${{ secrets.ENV }}" | base64 --decode > .env
          echo "Verifying .env file:"
          ls -la .env  # List file to confirm it exists
      
      - name: Build Android
        id: sign_app
        run: |
          flutter pub get
          flutter build appbundle --release --dart-define-from-file=.env
          flutter build apk --release --dart-define-from-file=.env
      
      - name: Upload TO Play Store ( Internal Testing / Production )
        uses: r0adkll/upload-google-play@v1.1.3
        with: 
            serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
            packageName: "xyz.deepeshkalura.learnza"
            releaseFiles: build/app/outputs/bundle/release/app-release.aab
            mappingFile: ./build/app/outputs/mapping/release/mapping.txt
            track: 'internal'  
      
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ needs.prepare-release.outputs.new_version }} \
            --title "Release v${{ needs.prepare-release.outputs.new_version }}" \
            --notes "Deployment to Play Store - ${{ github.event.inputs.release_type }}"